### PR TITLE
fixed a bug with the wreath product construction

### PR DESCRIPTION
**Pull request by goens**
The wreath product construction ignored trivial subgroups, yielding the wrong symmetry group for architectures with single processors (even though the isomorphy class was correct). This actually removes non-trivial symmetries from the final archgraph (even if the indices were to be corrected, which they were not). Imagine an architecture with 2 clusters, each with 3 cores: 2 of type A and 1 of type B. Then we lose the automorphism that maps B1 to B2.

### CODE REVIEW

**Comment by Time0o** [comment]
This change breaks the tests. I'm wondering whether that is because something else is wrong or this needs to be done differently. I will look into it.

**Comment by Time0o** [comment]
If I remember correctly, those lines are in there because I wanted the function to behave like GAP's `WreathProduct` and not like GAP's `StandardWreathProduct` because the latter didn't produce the automorphism groups that I expected for the HAEC graph or something like that.

**Comment by goens** [comment]
That's interesting, it shouldn't break the tests actually. I looked at it just now and I'm pretty sure it's because it was working as intended, but that's not what we need for the use case. Specifically you have this test in `perm_group` which I think should break: 
```
TEST(PermGroupCombinationTest, CanConstructWreathProduct)
{
  std::vector<std::pair<PermGroup, PermGroup>> wreath_products {
 /* ... */
    {
      PermGroup(9,
        {
          Perm(9, {{1, 4, 7}}),
          Perm(9, {{1, 5, 9}})
        }
      ),
      PermGroup(3,
        {
          Perm(3, {{1, 2, 3}})
        }
      )
    },
/*...*/
  };

  PermGroup expected_wreath_products[] = {
 /* ... */
    PermGroup(15,
      {
        Perm(15, {{1, 2, 4}}),
        Perm(15, {{1, 3, 5}}),
        Perm(15, {{1, 6, 11}, {2, 7, 12},
                  {3, 8, 13}, {4, 9, 14},
                  {5, 10, 15}}),
        Perm(15, {{11, 12, 14}}),
        Perm(15, {{11, 13, 15}}),
        Perm(15, {{6, 7, 9}}),
        Perm(15, {{6, 8, 10}})
      }
    ),
/* ... */
```
The original wreath product is acting on 3*9 = 27 points, but the expected result acts on 3*5 = 15 points, because the first group acts as identity on the points 2,3,6. Actually this way `num_processors` was also broken.

The problem is that we don't want the `wreath_product` construction to be correct *up to isomorphism*, we want it to be the actual wreath product construction there because those processors still exist. If we wanted to use this, we would need to have a non-trivial action on the platforms and mapping spaces that remembers the processors that were deleted. I think the patch I proposed is easier than implementing these actions, even though the latter would perhaps be nicer, it's a lot of work for currently little gain.

**Comment by Time0o** [comment]
I agree. I actually just looked at the GAP documentation and they explain how to use `WreathProduct` with permutation groups whose domains are not equal to their moved sets (which is what we _should_ have here, currently my wreath product implementation behaves just like GAP's and disregards points not in the moved set). I will figure out how to do this correctly in GAP so I can construct some new test cases for the corrected `PermGroup::wreath_product` before I merge this.

Also, from your example I created this script:

```python
ag_proto = pympsym.ArchGraph(directed=False)                                  
ag_proto.add_processors(2, 'p1')                                         
ag_proto.add_processor('p2')                                             
ag_proto.fully_connect('p_c') 
                                                                                
ag_super = pympsym.ArchGraph(directed=False)                                  
ag_super.add_processors(2, 'cl')                                         
ag_super.fully_connect('cl_c')   
```

And with your patch the automorphism group I get is generated by `{(1, 4)(2, 5)(3, 6), (4, 5)}`. Is that correct? Why is `{(1,2)(4,5), (1,4), (3,6)}` not a correct generating set? That's what I would have though it should be.

**Comment by goens** [comment]
The point is that GAP has a different use-case: they care about the groups themselves, which are best described through their isomorphism classes. We care about the action more so that the group. I would not do the construction they do with the transitive overgroup, that would be pretty pointless for us, since we have more use for the action than for the group construction. The only reason to change would be efficiency, and in that case a specialized action (currently we're doing what gaps calls `onPoints` and `onTuples`, and we'd then specify a function that basically fixes the correspondence) I think honestly the best thing to do is just leave the construction as with this patch, since it best fits our use-case. 

Yep, that generating set is correct. In your example of a generating set, you could swap (3,6) but leave 1,2,4,5 in the same place: you need to swap the whole cluster at once. So, in your example, the mappings [1,2,3] and [1,2,6] would be in the same orbit, but in one all cores are mapped to the same cluster, in the other one they're not.

**Pull request merged**
